-d C:\Users\ahmet\OneDrive\Belgeler\alarm_clock_project\impl\gwsynthesis\alarm_clock_project.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst C:\Users\ahmet\OneDrive\Belgeler\alarm_clock_project\src\alarm_clock_project.cst
-cfg C:\Users\ahmet\OneDrive\Belgeler\alarm_clock_project\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
