-d C:\Users\ahmet\OneDrive\Belgeler\traffic_lights\impl\gwsynthesis\traffic_lights.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst C:\Users\ahmet\OneDrive\Belgeler\traffic_lights\src\traffic_lights.cst
-cfg C:\Users\ahmet\OneDrive\Belgeler\traffic_lights\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
